name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --release

    - name: Upload Release Binary
      uses: actions/upload-artifact@v4
      with:
        name: release-binary
        path: target/release/bucksaw.exe
